#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.1.1"

# Which extra RobotPy components should be installed
components = [
    "commands2",
#    "phoenix6",
#    "robotpy-pathplannerlib",
#    "robotpy-rev"
]

requires = [
    "phoenix6==26.1.0",
    "robotpy-pathplannerlib==2026.1.1",
    "robotpy-rev==2026.0.0"
]