#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.3.2.2"

# Which extra RobotPy components should be installed
robotpy_extras = [
    "commands2",
    "phoenix6",
    "robotpy-pathplannerlib",
    "robotpy-rev"
]

requires = [

]